---
name: schedule
on:
  push:
    branches: ['*pflash*']
  schedule:
  # disable scheduling of `ovmf-resolution` test for now as the default settings are currently good enough,
  # see https://progress.opensuse.org/issues/197930#note-19
  # - cron: '23 5 * * 0'
  workflow_dispatch:

jobs:
  schedule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: registry.opensuse.org/home/okurz/container/containers/tumbleweed:openQA-client
    env:
      OPENQA_API_KEY: ${{ secrets.OPENQA_API_KEY }}
      OPENQA_API_SECRET: ${{ secrets.OPENQA_API_SECRET }}
    steps:
      - uses: actions/checkout@v6
      - run: |
          ./trigger-pflash-test
